### ISSUE TITLE
睡眠時間の計測

### ISSUE THREAD

**Issue by ka0ru19** [gogo0716/catsleeping#2]
画面が下になってる状態の時間を計測せよ

2/14のスクールまで。

**Comment by gogo0716** [comment]
ヒントといううか説明的なのをください

**Comment by ka0ru19** [comment]
ヒント：
画面が暗くなった時と明るくなった時に時刻を取得してその時刻の差分を計算するといいかも

**Comment by ka0ru19** [comment]
ヒント２：
NSDate()

**Comment by gogo0716** [comment]
昨日と一昨日一応やったけどわからなかったから教えてください

**Comment by ka0ru19** [comment]
👍

**Comment by ka0ru19** [comment]
1. 近接した時刻を取得してprint
2. 離れた時の時刻を取得してprint
3. ２つの時刻の差分を計算してprint

**Comment by gogo0716** [comment]
終わった
